var firstLink="https://yahoo.com",createLinks=[],list=[],pageList=[],currentPage=1,numberPerPage=20,numberOfPages=0;for(i=0;20>i;i++)createLinks.push(firstLink);function load(a){var b=createLinks;if(""!==a){var c=JSON.parse(localStorage.getItem("storedLinks"));null!==c?(c.push(a),localStorage.setItem("url",a),localStorage.setItem("storedLinks",JSON.stringify(c))):(b.push(a),localStorage.setItem("storedLinks",JSON.stringify(b)));pushedLink()}else unpushedLink();makeList();loadList()}
function unpushedLink(){var a=createLinks,b=localStorage.getItem("storedLinks");null!==b?updateList(JSON.parse(b)):updateList(a)}function pushedLink(){var a=localStorage.getItem("storedLinks");updateList(JSON.parse(a))}
function updateList(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];void 0!==d&&(b+="<li class='urls'><span class='material-icons md-16 edit' data-toggle='modal' data-target='#myModal' onClick='editUrl("+c+")'>edit</span><a href='"+d+"' target='_blank'>"+d+"</a><span class='material-icons md-16 edit' data-toggle='modal' data-target='#myModal1' onClick='deleteUrl("+c+")'>delete</span></li>")}$("#myList").html(b)}
function validURL(a){return!!/^(https?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$/i.test(a)}function isValidHttpUrl(a){try{var b=new URL(a)}catch(c){return!1}return"http:"===b.protocol||"https:"===b.protocol}
function checkURL(){var a=$("#overview").val(),b=document.getElementById("overview");validURL(a)&&isValidHttpUrl(a)?($("#overview").addClass("success"),$("#errorMessage").removeClass("displayMessage"),$("#errorMessage").addClass("hideMessage"),b.setCustomValidity(""),document.getElementById("myForm").action="./review.html",update()):($("#overview").addClass("error"),$("#errorMessage").removeClass("hideMessage"),$("#errorMessage").addClass("displayMessage"),b.setCustomValidity("I am expecting an URL!"))}
function review(){var a=localStorage.getItem("url");document.getElementById("reviewUrl").innerHTML=a}function returnButton(){window.history.back()}function update(){var a=$("#overview").val();load(a)}function edit(){}function makeList(){var a=createLinks,b=localStorage.getItem("storedLinks");list=null!==b?JSON.parse(b):a;numberOfPages=getNumberOfPages()}function getNumberOfPages(){return Math.ceil(list.length/numberPerPage)}function nextPage(){currentPage+=1;loadList()}
function previousPage(){--currentPage;loadList()}function firstPage(){currentPage=1;loadList()}function lastPage(){currentPage=numberOfPages;loadList()}function loadList(){var a=(currentPage-1)*numberPerPage;pageList=list.slice(a,a+numberPerPage);drawList();check()}
function drawList(){document.getElementById("myList").innerHTML="";for(r=0;r<pageList.length;r++)document.getElementById("myList").innerHTML+="<li class='urls'><span class='material-icons md-16 edit' data-toggle='modal' data-target='#myModal' onClick='editUrl("+r+")'>edit</span><a href='"+pageList[r]+"' id='link"+r+"' target='_blank'>"+pageList[r]+"</a><span class='material-icons md-16 edit' data-toggle='modal' data-target='#myModal1' onClick='deleteUrl("+r+")'>delete</span></li> "}
function check(){document.getElementById("next").disabled=currentPage==numberOfPages?!0:!1;document.getElementById("previous").disabled=1==currentPage?!0:!1;document.getElementById("first").disabled=1==currentPage?!0:!1;document.getElementById("last").disabled=currentPage==numberOfPages?!0:!1}function editUrl(a){var b=$("#link"+a).prop("href");sessionStorage.setItem("id",a);setTimeout(function(){$("#editUrl").val(b)},1E3)}
function deleteUrl(a){var b=$("#link"+a).prop("href");sessionStorage.setItem("deleteId",a);$("#deleteUrls").text(b)}
function deleteAndUpdateUrl(){var a=JSON.parse(localStorage.getItem("storedLinks")),b=parseInt(sessionStorage.getItem("deleteId"));if(null!==a)for(var c=0;c<a.length;c++){if(c===b){a.splice(c,1);localStorage.setItem("storedLinks",JSON.stringify(a));update();break}}else for(c=0;c<createLinks.length;c++)if(c===b){createLinks.splice(index,c);localStorage.setItem("storedLinks",JSON.stringify(createLinks));update();break}}
function updateUrl(){var a=JSON.parse(localStorage.getItem("storedLinks")),b=parseInt(sessionStorage.getItem("id")),c=$("#editUrl").val();if(null!==a)for(var d=0;d<a.length;d++){if(d===b){a[d]=c;localStorage.setItem("storedLinks",JSON.stringify(a));break}}else for(d=0;d<createLinks.length;d++)if(d===b){createLinks[d]=c;localStorage.setItem("storedLinks",JSON.stringify(createLinks));break}pushedLink()};